"""Shared registry for Studio API and inference worker."""
MODELS = {
    'medical': {'name': 'Médical V8', 'project': 'LibraryBrainMedical', 'release': 'LibraryBrain-Medical-Reader-v8', 'variant': 'medical-reader-v8', 'runtime': 'medical_documentary_v8', 'worker': 'medical_documentary_v8_worker.py', 'supports_training': False, 'category': None, 'description': 'Retrouver des passages sourcés dans le catalogue médical sélectionné et 15 publications HAS datées. Extraits dans leur langue d’origine, avec leur contexte.', 'domains': ['Recherche documentaire', 'Comparaison des textes', 'Sources et dates']},
    'legal': {'name': 'Juridique V3', 'project': 'LibraryBrainLegal', 'release': 'LibraryBrain-Legal-LoRA-v3', 'variant': 'legal-v3', 'runtime': 'legal_lora', 'worker': 'legal_worker.py', 'supports_training': False, 'category': None, 'description': 'Lire et citer les codes français datés. LoRA V3 expérimental ; droit civil absent du corpus.', 'domains': ['Pénal', 'Procédure pénale', 'Routier']},
    'research': {'name': 'LibraryBrain Research', 'project': 'LibraryBrainResearch', 'release': 'LibraryBrain-Research-4B-v0.1', 'variant': 'research4b', 'category': None, 'description': 'Comprendre, croiser et citer votre bibliothèque.', 'domains': ['Recherche', 'Synthèse', 'Sources']},
    'music': {'name': 'KlodyMusic', 'project': 'KlodyMusic', 'release': 'KlodyMusic-4B-v0.1', 'variant': 'klodymusic', 'category': 'Musique', 'description': 'Explorer la composition, la production et le son.', 'domains': ['Composition', 'Mixage', 'Théorie']},
    'business': {'name': 'Business Pratique', 'project': 'BusinessPratique', 'release': 'BusinessPratique-4B-v0.1', 'variant': 'business4b', 'max_output_tokens': 1200, 'category': ['Business', 'Management', 'Économie', 'Entrepreneuriat', 'Logistique', 'Leadership', 'Leadership development', 'Coaching'], 'description': 'Construire votre offre, trouver vos clients et piloter votre activité.', 'domains': ['Offre & vente', 'Gestion', 'Organisation']},
    'code': {'name': 'KlodyCode / IA', 'project': 'KlodyCode', 'release': 'KlodyCode-4B-v0.1', 'variant': 'klodycode', 'max_output_tokens': 1600, 'category': ['Informatique', 'Intelligence_artificielle', 'IA', 'AI', 'GitHub'], 'description': 'Comprendre le code, concevoir vos outils et explorer l’IA avec vos sources.', 'domains': ['Code & tests', 'RAG & agents', 'Données & IA']},
}
